---
AllCops:
  NewCops: enable
  TargetRubyVersion: '2.6'

Layout/LineLength:
  Max: 100
  Exclude:
    - test/**/*

Metrics/AbcSize:
  Exclude:
    - test/**/*

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/Documentation:
  Enabled: false
