---
AllCops:
  NewCops: enable
  TargetRubyVersion: '2.6'

Layout/LineLength:
  Max: 100

Metrics/AbcSize:
  Exclude:
    - test/**/*

Metrics/MethodLength:
  Exclude:
    - test/**/*

Style/Documentation:
  Enabled: false
